name: Rapport Quotidien

on:
  workflow_dispatch:
  schedule:
    - cron: '45 15 * * 1-5'

jobs:
  rapport-quotidien:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Installer dependances
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml openpyxl
    
    - name: Lancer Rapport Quotidien
      env:
        BRVM_EMAIL: ${{ secrets.BRVM_EMAIL }}
        RECIPIENTS: ${{ secrets.RECIPIENTS }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
      run: |
        python automatisation_brvm_VERSIONNED_V3_FINAL.py
