name: Scraper Dividendes

on:
  workflow_dispatch:
  schedule:
    - cron: '39 13 * * 1-5'  # 12h30 GMT → 14h30 réel Abidjan (décalage -2h)

jobs:
  scraper-dividendes:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Installer dependances
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml
    
    - name: Lancer Scraper Dividendes
      run: |
        python scraper_brvm_dividendes.py

